import React from 'react'

import Head from 'next/head'

export const PageHead = (): JSX.Element => (
  <Head>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="./favicon.ico" />
  </Head>
)
