// Modules
import React from 'react'
import Head from 'next/head'

// *************** Type *************** //
type Props = {
  title?: string
}

export const PageHead = (props: Props) => (
  // *************** JSX *************** //
  <Head>
    <title>{props.title && `${props.title} | `} asakatsu</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="./favicon.ico" />
  </Head>
)
