// Modules
import React from "react"
import Head from "next/head"

// *************** Type *************** //
type Props = {
  title: string
}

export const PageHead = (
  props: Props
) => {
  // *************** JSX *************** //
  return (
    <Head>
      <title>{props.title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="../../public/favicon.ico" />
    </Head>
  )
}